[project]
name = "listen"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "mne-qt-browser>=0.7.0",
    "pandas>=2.2.3",
    "pyqt6>=6.9.0",
]
